service: serverless-go-crud

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-southeast-1

package:
 individually: true
 exclude:
   - ./**

functions:
  hello:
    handler: bin/handlers/addTodo
    package:
     include:
       - ./bin/handlers/addTodo
    events:
      - http:
          path: todos
          method: post
          cors: true
